### ISSUE TITLE
Documentation help

### ISSUE THREAD

**Issue by azlux** [drone-plugins/drone-irc#15]
Hi,
The Readme said the doc is here : http://plugins.drone.io/drone-plugins/drone-irc/ But the IRC part didn't exist.
Is this plugins still supported ?
There are no exemple/doc about the .drone.yml config to enable IRC notification.
Can you give some help ?

Az

**Comment by tboerger** [comment]
Nobody has documented the available attributes https://github.com/drone-plugins/drone-irc/blob/master/main.go#L21-L77 so far...

```
steps:
- name: irc
  image: plugins/irc
  settings:
    nick: drone-bot
    channel: #my-awesome-project 
    host: irc.example.com 
    port: 6667
```
